const bcrypt = require('bcryptjs');
const data = {
    users: [
        {
            name: 'Alok Dubey',
            email: 'alok73327@gmail.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: true
        }
    ], 
    products: [
        {
            name: 'Quinidine',
            category: 'Tablet',
            image: '/images/p1.jpg',
            price: 563,
            countInStock: 310,
            brand: 'Glaxo Smithkline',
            rating: 4.3,
            numReviews: 10,
            description: 'Quinidine is a medicine used to treat certain types of arrhythmia (abnormal heart rhythm). It restores normal heart rhythm by blocking abnormal electrical signals in the heart. This helps to maintain a regular and steady heartbeat.',
        },
        {
            name: 'Lipophase',
            category: 'Capsule',
            image: '/images/p2.jpg',
            price: 218,
            countInStock: 220,
            brand: 'Franco Indian Pharmaceuticals Ltd.',
            rating: 4.0,
            numReviews: 10,
            description: 'Orlistat is a medicine used in the treatment of obesity. It helps the body in blocking the absorption of fats from the small intestines and stomach.',
        },
        {
            name: 'Hydrogen Peroxide',
            category: 'Agrawal',
            image: '/images/p3.jpg',
            price: 24,
            countInStock: 200,
            brand: 'Franco Indian Pharmaceuticals Ltd.',
            rating: 4.1,
            numReviews: 17,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        },
        {
            name: 'Hexinol',
            category: 'Agrawal',
            image: '/images/p4.jpg',
            price: 78,
            countInStock: 15,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 14,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        },
        {
            name: 'Aptamol',
            category: 'Injection',
            image: '/images/p5.jpg',
            price: 65,
            countInStock: 5,
            brand: 'Agrawal',
            rating: 4.5,
            numReviews: 10,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        },
        {
            name: 'Alizole',
            category: 'Injection',
            image: '/images/p6.jpg',
            price: 139,
            countInStock: 12,
            brand: 'Allenge India',
            rating: 4.5,
            numReviews: 15,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        },        
        {
            name: 'Zetam',
            category: 'Tablet',
            image: '/images/p1.jpg',
            price: 85,
            countInStock: 132,
            brand: 'Alembic Ltd',
            rating: 4.5,
            numReviews: 15,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        },        
        {
            name: 'Dubatan',
            category: 'Capsule',
            image: '/images/p2.jpg',
            price: 139,
            countInStock: 412,
            brand: 'Alembic Ltd',
            rating: 4.5,
            numReviews: 15,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        },        
        {
            name: 'Binacid',
            category: 'Capsule',
            image: '/images/p3.jpg',
            price: 139,
            countInStock: 12,
            brand: 'Biocin Helthcare',
            rating: 4.5,
            numReviews: 15,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        },        
        {
            name: 'Richem',
            category: 'Syrup',
            image: '/images/p4.jpg',
            price: 58,
            countInStock: 12,
            brand: 'Biocin Helthcare',
            rating: 4.6,
            numReviews: 15,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        },        
        {
            name: 'Aziclen',
            category: 'Capsule',
            image: '/images/p5.jpg',
            price: 87,
            countInStock: 302,
            brand: 'Biocin Helthcare',
            rating: 4.5,
            numReviews: 15,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        },
    ],
};

module.exports = data;
